# Generated by Django 5.2.4 on 2025-08-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='business_hours',
            field=models.JSONField(default=dict, help_text='\n        {\n            "start": "09:00",\n            "end": "18:00"\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='funding',
            name='schedule',
            field=models.JSONField(default=dict, help_text='\n        {\n            "start": "2025-07-21",\n            "end": "2025-08-24"\n        }\n        '),
        ),
    ]
