# Generated by Django 5.2.4 on 2025-08-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0002_alter_funding_business_hours_alter_funding_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='funding/founder_image'),
        ),
    ]
