# Generated by Django 5.2.4 on 2025-08-22 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0002_alter_funding_business_hours_alter_funding_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='amount_description',
            field=models.CharField(help_text='예산 사용 계획서', max_length=1000),
        ),
        migrations.AlterField(
            model_name='funding',
            name='bank_account',
            field=models.CharField(help_text='00000000000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='funding',
            name='contact',
            field=models.URLField(help_text='http://localhost:8000', max_length=50),
        ),
        migrations.AlterField(
            model_name='funding',
            name='content',
            field=models.CharField(blank=True, help_text='프로젝트 내용', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='expected_opening_date',
            field=models.CharField(help_text='2025-08', max_length=7, validators=[django.core.validators.RegexValidator(message='YYYY-MM 형식으로 입력하세요.', regex='^\\d{4}-(0[1-9]|1[0-2])$')]),
        ),
        migrations.AlterField(
            model_name='funding',
            name='expected_problem',
            field=models.CharField(help_text='예상되는 어려움', max_length=500),
        ),
        migrations.AlterField(
            model_name='funding',
            name='founder_description',
            field=models.CharField(help_text='창업자 소개', max_length=500),
        ),
        migrations.AlterField(
            model_name='funding',
            name='founder_name',
            field=models.CharField(help_text='창업자 이름', max_length=30),
        ),
        migrations.AlterField(
            model_name='funding',
            name='policy',
            field=models.CharField(help_text='프로젝트 정책', max_length=500),
        ),
        migrations.AlterField(
            model_name='funding',
            name='reward_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='schedule_description',
            field=models.CharField(help_text='프로젝트 일정', max_length=1000),
        ),
        migrations.AlterField(
            model_name='funding',
            name='summary',
            field=models.CharField(blank=True, help_text='프로젝트 요약', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='funding',
            name='title',
            field=models.CharField(help_text='프로젝트 제목', max_length=50),
        ),
    ]
