# Generated by Django 5.2.4 on 2025-08-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0002_alter_funding_business_hours_alter_funding_schedule'),
    ]

    operations = [
    ]
