# Generated by Django 5.2.4 on 2025-08-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0003_alter_funding_amount_description_and_more'),
        ('fundings', '0003_alter_funding_founder_image'),
    ]

    operations = [
    ]
