# Generated by Django 5.2.4 on 2025-08-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0004_merge_20250822_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='business_name',
            field=models.CharField(default='상호명', help_text='상호명', max_length=20),
            preserve_default=False,
        ),
    ]
