# Generated by Django 5.2.4 on 2025-08-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0004_merge_20250821_2334'),
        ('fundings', '0005_funding_business_name'),
    ]

    operations = [
    ]
