# Generated by Django 5.2.4 on 2025-08-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundings', '0006_merge_20250824_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.PositiveIntegerField(choices=[(5000, '5천원'), (10000, '1만원'), (30000, '3만원'), (50000, '5만원')]),
        ),
    ]
