# Generated by Django 5.2.4 on 2025-08-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_founder_industry_alter_proposer_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='business_hours',
            field=models.JSONField(default=dict, help_text='\n        {\n            "start": "09:00",\n            "end": "18:00"\n        }\n        '),
        ),
    ]
