# Generated by Django 5.2.4 on 2025-09-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='position',
            field=models.JSONField(default=dict, help_text='\n        {\n            "latitude": 37.56661,\n            "longitude": 126.978388\n        }\n        '),
        ),
    ]
