# Generated by Django 5.2.5 on 2025-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='industry',
            field=models.CharField(choices=[('FOOD_DINING', '외식/음식점'), ('CAFE_DESSERT', '카페/디저트'), ('PUB_BAR', '주점'), ('CONVENIENCE_RETAIL', '편의점/소매'), ('GROCERY_MART', '마트/식료품'), ('BEAUTY_CARE', '뷰티/미용'), ('HEALTH_FITNESS', '건강'), ('FASHION_GOODS', '패션/잡화'), ('HOME_LIVING_INTERIOR', '생활용품/가구'), ('HOBBY_LEISURE', '취미/오락/여가'), ('CULTURE_BOOKS', '문화/서적'), ('PET', '반려동물'), ('LODGING', '숙박'), ('EDUCATION_ACADEMY', '교육/학원'), ('AUTO_TRANSPORT', '자동차/운송'), ('IT_OFFICE', 'IT/사무'), ('FINANCE_LEGAL_TAX', '금융/법률/회계'), ('MEDICAL_PHARMA', '의료/의약'), ('PERSONAL_SERVICES', '생활 서비스'), ('FUNERAL_WEDDING', '장례/예식'), ('PHOTO_STUDIO', '사진/스튜디오'), ('OTHER_RETAIL', '기타 판매업'), ('OTHER_SERVICE', '기타 서비스업')], max_length=24),
        ),
    ]
