# Generated by Django 5.2.4 on 2025-08-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_proposal_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='business_hours',
            field=models.JSONField(default=dict, help_text='\n        {\n            "start": "09:00",\n            "end": "18:00"\n        }\n        '),
        ),
    ]
