# Generated by Django 5.2.4 on 2025-08-25 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fundings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('version', models.CharField(default='2022-11-16', max_length=10)),
                ('type', models.CharField(choices=[('NORMAL', '일반 결제'), ('BILLING', '자동결제'), ('BRANDPAY', '브랜드페이')], default='NORMAL', max_length=10)),
                ('order_id', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('order_name', models.CharField(max_length=100)),
                ('m_id', models.CharField(max_length=14)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('method', models.CharField(blank=True, choices=[('카드', 'Card'), ('가상계좌', 'Virtual Account'), ('간편결제', 'Easy Pay'), ('휴대폰', 'Mobile Phone'), ('계좌이체', 'Transfer'), ('문화상품권', 'Gift Certificate'), ('도서문화상품권', 'Culture Gift Cert'), ('게임문화상품권', 'Game Gift Cert')], max_length=20, null=True)),
                ('total_amount', models.PositiveIntegerField(editable=False)),
                ('balance_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('READY', '요청 생성'), ('IN_PROGRESS', '승인 중'), ('WAITING_FOR_DEPOSIT', '입금 대기'), ('DONE', '승인 완료'), ('CANCELED', '전체 취소'), ('PARTIAL_CANCELED', '부분 취소'), ('ABORTED', '승인 실패/중단'), ('EXPIRED', '만료')], default='READY', max_length=32)),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('use_escrow', models.BooleanField()),
                ('last_transaction_key', models.CharField(blank=True, max_length=64, null=True)),
                ('supplied_amount', models.PositiveIntegerField()),
                ('vat', models.PositiveIntegerField()),
                ('culture_expense', models.BooleanField()),
                ('tax_free_amount', models.PositiveIntegerField()),
                ('tax_exemption_amount', models.PositiveIntegerField()),
                ('is_partial_cancelable', models.BooleanField()),
                ('card', models.JSONField(blank=True, default=dict, null=True)),
                ('virtual_account', models.JSONField(blank=True, default=dict, null=True)),
                ('secret', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.JSONField(blank=True, default=dict, null=True)),
                ('gift_certificate', models.JSONField(blank=True, default=dict, null=True)),
                ('transfer', models.JSONField(blank=True, default=dict, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='결제 요청 시 추가할 수 있는 metadata (최대 5개, key 최대 40자, value 최대 500자)', null=True)),
                ('receipt', models.JSONField(blank=True, default=dict, null=True)),
                ('checkout', models.JSONField(blank=True, default=dict, null=True)),
                ('easy_pay', models.JSONField(blank=True, default=dict, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('failure', models.JSONField(blank=True, default=dict, null=True)),
                ('discount', models.JSONField(blank=True, default=dict, null=True)),
                ('items_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('donation_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='fundings.funding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='accounts.proposer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(help_text='주문번호(영문/숫자 6~64자)', max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)])),
                ('item', models.JSONField(default=dict, help_text='구매 리워드 스냅샷(JSON)')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='fundings.funding')),
                ('proposer_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='fundings.proposerreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='accounts.proposer')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='pays.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('receipt_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('소득공제', 'Income Deduction'), ('지출증빙', 'Expense Proof')], max_length=4)),
                ('issue_number', models.CharField(max_length=9)),
                ('receipt_url', models.URLField()),
                ('business_number', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(choices=[('CONFIRM', '발급'), ('CANCEL', '취소')], max_length=7)),
                ('amount', models.PositiveIntegerField()),
                ('tax_free_amount', models.PositiveIntegerField()),
                ('issue_status', models.CharField(choices=[('IN_PROGRESS', '발급 진행 중'), ('COMPLETED', '발급 완료'), ('FAILED', '발급 실패')], max_length=11)),
                ('customer_identity_number', models.CharField(max_length=30)),
                ('requested_at', models.DateTimeField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipts', to='pays.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_amount', models.PositiveIntegerField()),
                ('cancel_reason', models.CharField(max_length=200)),
                ('tax_free_amount', models.PositiveIntegerField()),
                ('tax_exemption_amount', models.PositiveIntegerField()),
                ('refundable_amount', models.PositiveIntegerField()),
                ('card_discount_amount', models.PositiveIntegerField()),
                ('transfer_discount_amount', models.PositiveIntegerField()),
                ('easy_pay_discount_amount', models.PositiveIntegerField()),
                ('canceled_at', models.DateTimeField()),
                ('transaction_key', models.CharField(max_length=64)),
                ('receipt_key', models.CharField(blank=True, max_length=200, null=True)),
                ('cancel_status', models.TextField()),
                ('cancel_request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cancel', to='pays.payment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('funding', 'user'), name='unique_funding_user'),
        ),
    ]
