# Generated by Django 5.2.4 on 2025-08-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_key', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=50)),
                ('card_company', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField()),
                ('currency', models.CharField(default='KRW', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_amount', models.IntegerField()),
                ('canceled_at', models.DateTimeField()),
                ('cancel_status', models.CharField(max_length=50)),
                ('transaction_key', models.CharField(max_length=64)),
                ('receipt_key', models.CharField(blank=True, max_length=200, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancels', to='pays.payment')),
            ],
        ),
    ]
