# Generated by Django 5.2.4 on 2025-08-24 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_founder_business_hours'),
        ('fundings', '0007_alter_reward_amount'),
        ('pays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(help_text='주문번호(영문/숫자 6~64자)', max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(6)])),
                ('item', models.JSONField(default=dict, help_text='구매 리워드 스냅샷(JSON)')),
                ('funding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='fundings.funding')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='pays.payment')),
                ('proposer_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='fundings.proposerreward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='accounts.proposer')),
            ],
        ),
    ]
