# Generated by Django 5.2.4 on 2025-08-19 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('FUNDING', '펀딩'), ('REWARD', '리워드')], max_length=7)),
                ('path_variable', models.CharField(max_length=21)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder_notification', to='accounts.founder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('FUNDING', '펀딩'), ('REWARD', '리워드')], max_length=7)),
                ('path_variable', models.CharField(max_length=21)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposer_notification', to='accounts.proposer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
